### ISSUE TITLE
Wrong total money invested

### ISSUE THREAD

**Issue by maysam35** [jmfernandes/robin_stocks#10]
I kept getting wrong total money invested until I realized I have a canceled transaction. In case anyone has the same issue, just modify the deposit and withdrawal definition to make sure they are "completed". For example:

deposits = sum(float(x['amount']) for x in allTransactions if (x['direction'] == 'deposit') and (x['state'] == 'completed'))
withdrawals = sum(float(x['amount']) for x in allTransactions if (x['direction'] == 'withdraw') and (x['state'] == 'completed'))

https://github.com/jmfernandes/robin_stocks/blob/c8ba2e5a5d98bf54fd42a9ba1fce414c7c8f2a8a/examples/get_accurate_gains.py#L24

**Comment by jmfernandes** [comment]
Thanks for this. I updated the code in Github.
