### ISSUE TITLE
0.9.8 *inputsymbols update breaks the usage of strings 

### ISSUE THREAD

**Issue by ImpetusSports** [jmfernandes/robin_stocks#11]
0.9.8 *inputsymblos update breaks the usage of strings 

While trying to pass though stock symbol for Apple it returns the company for stock symbol "P"

I have found it does this for all company strings i pass through.

Example:
code:
stockTicker = 'AAPL'
quote = robinhood.stocks.get_quotes(stockTicker, info=None)
print('Quote:', quote)

output:
Quote: [{'ask_price': '70.380000', 'ask_size': 3300, 'bid_price': '70.370000', 'bid_size': 2500, 'last_trade_price': '70.380000', 'last_extended_hours_trade_price': '70.380000', 'previous_close': '69.900000', 'adjusted_previous_close': '69.900000', 'previous_close_date': '2019-01-10', 'symbol': 'A', 'trading_halted': False, 'has_traded': True, 'last_trade_price_source': 'consolidated', 'updated_at': '2019-01-11T21:02:52Z', 'instrument': 'https://api.robinhood.com/instruments/2095bd69-d441-4da8-a014-5af9bcbf5394/'}, {'ask_price': '8.600000', 'ask_size': 6500, 'bid_price': '8.590000', 'bid_size': 28000, 'last_trade_price': '8.590000', 'last_extended_hours_trade_price': '8.590000', 'previous_close': '8.620000', 'adjusted_previous_close': '8.620000', 'previous_close_date': '2019-01-10', 'symbol': 'P', 'trading_halted': False, 'has_traded': True, 'last_trade_price_source': 'consolidated', 'updated_at': '2019-01-11T21:02:06Z', 'instrument': 'https://api.robinhood.com/instruments/d15643d2-545c-4b83-a290-f85fe4575b0e/'}, {'ask_price': '46.580000', 'ask_size': 6100, 'bid_price': '46.570000', 'bid_size': 1300, 'last_trade_price': '46.580000', 'last_extended_hours_trade_price': '46.580000', 'previous_close': '46.390000', 'adjusted_previous_close': '46.390000', 'previous_close_date': '2019-01-10', 'symbol': 'L', 'trading_halted': False, 'has_traded': True, 'last_trade_price_source': 'consolidated', 'updated_at': '2019-01-11T21:28:48Z', 'instrument': 'https://api.robinhood.com/instruments/0261820d-077e-4b8f-99e4-28afb01868e1/'}]

**Comment by jmfernandes** [comment]
Fixed in 0.9.8.2

Sorry, I changed inputSymbols to no longer be a variable length argument, and in the inputs_to_set() function I was looping over all elements in inputSymbols. That works if its an arguments list but when it's a string like "aapl" you get ["a","a","p","l"]
