### ISSUE TITLE
Issue with newest example - trying to use a different function, but need help with proper inputs

### ISSUE THREAD

**Issue by AmeliorateOr** [jmfernandes/robin_stocks#12]
`import robin_stocks as r
import os
import datetime
import time as t

'''
This is an example script that will print out options data every 10 seconds for 1 minute.
It also saves the data to a txt file. The txt file is saved in the same directory as this code.
'''

#!!! Fill out username and password
username = ''
password = ''
#!!!

login = r.login(username,password)

#!!! fill out the specific option information
strike = 150.0
date = "2019-06-21"
stock = "V"
optionType = "call" #or "put"
#!!!

# File saving variables
minutesToTrack = 1 #in minutes
PrintInterval = 10 #in seconds
endTime = t.time() + 60 * minutesToTrack
fileName = "options.txt"
writeType = "w" #or enter "a" to have it continuously append every time script is run
#

os.chdir(os.path.dirname(__file__))
path = os.getcwd()
filename = os.path.join(path,fileName)
fileStream = open(filename,mode=writeType)

while t.time() < endTime:
    time = str(datetime.datetime.now())
    #Both write and print the data so that you can view it as it runs.
    fileStream.write("\n")
    fileStream.write(time)
    print(time)
    #Get the data
    instrument_Data = r.get_option_instrument_data(stock,date,strike,optionType)
    market_Data = r.get_option_market_data(stock,date,strike,optionType)

    fileStream.write("\n")
    fileStream.write("{} Instrument Data {}".format("="*30,"="*30))
    print("{} Instrument Data {}".format("="*30,"="*30))
    #Instrument_Data is a dictionary, and the key/value pairs can be accessed with .items()
    for key, value in instrument_Data.items():
        fileStream.write("\n")
        fileStream.write("key: {:<25} value: {}".format(key,value))
        print("key: {:<25} value: {}".format(key,value))

    fileStream.write("\n")
    fileStream.write("{} Market Data {}".format("="*30,"="*30))
    print("{} Market Data {}".format("="*30,"="*30))

    for key, value in market_Data.items():
        fileStream.write("\n")
        fileStream.write("key: {:<25} value: {}".format(key,value))
        print("key: {:<25} value: {}".format(key,value))

    t.sleep(PrintInterval)

#make sure to close the file stream when you are done with it.
fileStream.close()`

---------------------------

I am getting an error while trying to use a different function for options data.

I get this error:

Traceback (most recent call last):
  File "C:\Users\Username\Desktop\Python\Version 2.1.py", line 63, in <module>
    for key, value in OptData.item():
AttributeError: 'list' object has no attribute 'item'

I am using the function, 
'#Get the data
    OptData = r.find_options_for_stock_by_expiration(symbol, expirationDate, optionType, info)

    fileStream.write('\n')

    fileStream.write("{} OptData".format("="*30,"="*30))
    print("{} OptData {}".format("="*30,"="*30))
    #OptData is a dictionary, and the key/value pairs can be accessed with .items()
    ## for key, value in OptData.items():
    for key, value in OptData.items():
        item(['chain_symbol'])'

when I try to print it though, I'm missing something in the code and it is giving me this error. Some direction would be greatly appreciated. I tried to just replace what you had input with what I'm trying to get, the line I get the error on is: item(['chain_symbol'])'

**Comment by jmfernandes** [comment]
The error says you are using .item() and it needs to be .items()

and if you want to use find_options_for_stock_by_expiration, that function returns a list of dictionaries instead of just a dictionary like get_option_market_data. So you will need to nest the for loop inside another for loop like this.

    for DictionaryInList in OptData:
        for key, value in DictionaryInList.items():
            item(['chain_symbol'])'

**Comment by jmfernandes** [comment]
read through this page to get more info on the difference between lists and dicts and how to access elements. section 5.6 goes over the looping techniques I use.

https://docs.python.org/3/tutorial/datastructures.html

There is also this page on how .items() works

http://www.tutorialspoint.com/python/dictionary_items.htm

but basically, if you want one specific dictionary value for a given key, you do dictionaryName['keyName'] and it returns what the value is. If you have a list of dictionaries then you probably want to loop over every element in the list in order to access the value In each dictionary. Alternatively, instead of getting a single value for a specific key name, you can loop over every key/value pair in a dictionary using .items(). It just depends if you want all values or just one, and whether you have direct reference to a dictionary or if that dictionary is stored in a list. Its also possible to have a list of lists or a dictionary that contains dictionaries, but there isn't a lot of that going on in the code.

**Comment by jmfernandes** [comment]
hmmm, unfortunately I wasn't able to replicate your error. This is the call I made

    options_data = r.find_options_for_stock_by_expiration('spy', '2019-02-01', 'put')

and it worked for me with no errors. I ran it with 'both' at the end too, and it worked.I suggest double checking all your variables.

**Comment by AmeliorateOr** [comment]
Ahh alright. I'm still working on learning saving using JSON. I'll post
when I get there. Thanks for the notification.

**Comment by AmeliorateOr** [comment]
# This code (using Python 3.7) will allow you to access options data as a JSON file and save it as often as you like by filing in some of the requirements below, comments below describe in detail.
# Special thanks to Jeremy for providing this .API!  

import robin_stocks as r
import time
import timeit    ## timer - be sure to import this to run timeit to make sure you can run this program at the desired intervals
import json


i = 0
while(i < 27): # 15 minute intervals throughout a trading day so 27 times so from 9:30 AM to 4:15 PM (or whatever time zone you're in)
                # NOTE: This must be started manually, as I have not set up an auto start.. ideally would be a cronjob for 9:30AM each morning 
    
    start = timeit.default_timer()    ## timer, should be before the function you want to run and calculate
    rest_time = 900 # seconds you'd like the program to delay before running again ( So 15 minutes - the time it takes to run this, defined below in time.sleep
    username = "*****" #enter in your username between the " "
    password = "*****" #enter in your password between the " "
    login = r.login(username, password)



    symbol = "SPY" # Enter symbol in string 
    expirationDate = "2019-03-08" # "YYYY-MM-DD" format , must be entered manually each day or week, you can not pull historical data requests
    optionType = "both" # "put" or "call" can also work, "both" gets both.


    # OptData is a dictionary with a list in it, which is why DictionaryInList is defined as such below
    OptData = r.find_options_for_stock_by_expiration(symbol, expirationDate, optionType) 

    for DictionaryInList in OptData: #To access the dictionaryinthelist from OptData use this for loop
        time_date = time.strftime('%m_%d_%Y_%H_%M') # this is to apply the time in the string of the filename, can change to whatever
                                                    ## format you like. See python time documentation for proper usage.
    
        with open(time_date+"_"+symbol+".json", "w") as f: # This will save the file as a json and with the time and symbol 
            json.dump(OptData, f)                           ## as file name. Run this program in the folder you want the files to save within. 
   
    
    stop = timeit.default_timer()    ## Timer end time. This is used to calculate the runtime_delay below to ensure you get an exact run so 
                                    ## many seconds which are defined in rest_time above. This compensates for the time it takes to run this program
                                    ## offsetting that by subtracting it in the runtime_delay and subtracting this delay from the rest_time to get
                                    ## an exact run every X seconds.
    runtime_delay = (stop - start)

    #print("Time: ", stop - start)    ## timer ; if you wanted to see how long this program takes to run, run this print statement
    time.sleep(rest_time - runtime_delay) # rest_time should be the time_interval you want the pull requests to be
    i += 1`
