### ISSUE TITLE
Historical crypto data not working past 3month

### ISSUE THREAD

**Issue by aharshbe** [jmfernandes/robin_stocks#121]
First, thank you for your awesome work.

Second, I am trying to request BTC historical data for a `year` or `5year` out from today and am getting the following error:
```
Successfully logged in.
400 Client Error: Bad Request for url: https://api.robinhood.com/marketdata/forex/historicals/3d961844-d360-45fc-989b-f6fca761d511/?interval=hour&span=year&bounds=24_7
None
```

- I am able to successfully request data from `day`, `week`, `month`, & `3month` but `year` and `5year` do not work.
- I am guessing it's because the Robinhood API has some sort of bug since it's a 400? Could also be because maybe hourly data isn't available for year and 5year? IDK. Posting here just in case.

**Comment by aharshbe** [comment]
- I just changed my request from `btc = r.get_crypto_historical("BTC","hour","year","24_7")` to `btc = r.get_crypto_historical("BTC","week","year","24_7")` and the request worked
- Do you think this is a limitation of the Robinhood API?

**Comment by sresam89** [comment]
nothing other than the above works.

**Comment by guptabhaskar** [comment]
I think Robinhood API made some changes. And now, interval='5minute' or '10minute' works only with span='day' or 'week'.

**Comment by aharshbe** [comment]
Thanks for the comments folks. Closing this out!
