### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by NebilI** [jmfernandes/robin_stocks#128]
Maybe I am missing something obvious, but when trying to  login with my correct information all of the functions I'm trying to use which are specific to my account do not return anything.

Even when I use incorrect information to login, I can still use the get_quotes function, but all other functions do not work as they return nothing. Any help would be much appreciated!

import robin_stocks

email = "email@gmail.com"
password = 'wrongpassword'

login = robin_stocks.authentication.login(username = email, password = password)

print("Login Info:\n")
for k, v in login.items():
    print(k, v, "\n")

print(robin_stocks.account.get_all_positions(info=None))
print(robin_stocks.get_quotes(["UAL"]))
print(robin_stocks.profiles.load_portfolio_profile())
print(robin_stocks.account.build_holdings())
print(robin_stocks.account.build_user_profile())
print(robin_stocks.profiles.load_portfolio_profile())\
robin_stocks.authentication.logout()

**Comment by Mikoh64us** [comment]
I just used that login instead.

login = r.authentication.login(username, password, expiresIn=86400, scope='internal', by_sms=True, store_session=True) 

your code works for me.

**Comment by sallaico** [comment]
Not all API calls require login info.

I had a login failure for anything account specific (i.e., get_all_positions). I was using Python 3.8.1 (which worked before). 

I got it around it by using Python 3.7.4 instead (no change to my code). However, after I did this, my pickle file did expire after every call and I was asked to reinput a verification code everytime.

**Comment by Mikoh64us** [comment]
Might very well be. I am running 3.7.6

**Comment by NebilI** [comment]
> I just used that login instead.
> 
> login = r.authentication.login(username, password, expiresIn=86400, scope='internal', by_sms=True, store_session=True)
> 
> your code works for me.

I had it work once before where it sent me the sms, but I realized I was trying to access an old account that I didn't want to use. Ever since it has not worked and the variable "login" holds the same info even when a fake password and username is passed and it does not show any type of failure of login in the dictionary that I can see. All of the prints aside from get_quotes (which I understand why that works) are empty lists / None.

I might also be confused but I think my username is just my email because otherwise I don't think I have anything I would refer to as a username.

I appreciate you taking the time to help me out!

**Comment by NebilI** [comment]
My friend, @jedouard98 , figured it out. It was an issue with the store session optional argument. In my case it should have been set to false.

login = robin_stocks.authentication.login('my_email@gmail.com','password123',store_session=False)

This fixed it. Hope this helps anyone with a similar issue!
