### ISSUE TITLE
get_stock_historicals returning a 404

### ISSUE THREAD

**Issue by imjonathan** [jmfernandes/robin_stocks#131]
`grep version setup.py`
      version='1.2.0',

```
import robin_stocks as rs
rs.login(username,password)
aapl = rs.stocks.get_stock_historicals('APPL', interval='hour', span='day')
```

404 Client Error: Not Found for url: https://api.robinhood.com/quotes/historicals/?symbols=APPL&interval=hour&span=day&bounds=regular

`aapl = rs.stocks.get_stock_historicals('APPL', interval='day', span='week')`

404 Client Error: Not Found for url: https://api.robinhood.com/quotes/historicals/?symbols=APPL&interval=day&span=week&bounds=regular

THANK YOU FOR THE AMAZING WORK!

**Comment by jmfernandes** [comment]
Apple stock is AAPL not APPL :p

**Comment by kreyusb** [comment]
^^ What @jmfernandes said.  But for my own sanity I double checked - `APPL` is not a valid ticker on any market.

**Comment by imjonathan** [comment]
> Apple stock is AAPL not APPL :p

YUP! Sorry, I got it right in the var, just not the ticker. Sorry about that!
