### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by Kei84** [jmfernandes/robin_stocks#141]
Can anyone help with this error?

***EDIT***
python3 is installed.
Installed using SUDO
pip install did not find robin-stocks/robin_stocks
===========================================

Error Messages reads as follows:

Processing /home/**ServerName**/RobinhoodBot/robin_stocks
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-yMWr3E/setup.py", line 6, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-yMWr3E/

**Comment by unacceptable** [comment]
https://stackoverflow.com/a/12541521

**Comment by jmfernandes** [comment]
Yeah did calling the file with
Python3 whateveryourfileis.py
Work?

**Comment by Kei84** [comment]
root@server:/home/username/robin_stocks# python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
root@server:/home/username/robin_stocks# apt-grt install setuptools

Command 'apt-grt' not found, did you mean:

  command 'apt-get' from deb apt (1.9.4ubuntu0.1)

Try: apt install <deb name>

root@server:/home/username/robin_stocks# apt-get install setuptools
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package setuptools

**Comment by unacceptable** [comment]
@Kei84,

Pardon only sending the link earlier.  I think when you are running the command sudo you are actually using python 2.  Also when installing setuptools I'd recommend using `pip` to install them not `apt`.  

https://pypi.org/project/setuptools/ <- pip install command here

Also please note you misspelled `apt-get`.  It really helps to read the command output before giving up.

Best of luck.
