### ISSUE TITLE
Full set of available options aren't being received

### ISSUE THREAD

**Issue by diegovargasf** [jmfernandes/robin_stocks#16]
Im using:
r.options.find_tradable_options_for_stock(ticker='MCHP')

To find all possible options availble, however, I'm only receiving options with expiration date in 2020, looking at the RH app I can see that there are many options with expiration dates in 2019.

**Comment by jmfernandes** [comment]
Fixed. Thanks for the message. keep in mind the function returns the instrument data of the option and some of the options returned will have the value "rhs_tradability" : "untradable". It seems there is some issues getting the market data for these options but i'm not sure why.
