### ISSUE TITLE
401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by Ali-Riaz** [jmfernandes/robin_stocks#162]
Hi everyone!

Encountering a really strange issue today when calling a few functions like get_fundamentals, get_stock_quote_by_symbol, get_latest_price etc. Even though I'm logged in successfully but when I try using the get_fundamentals for the stock with ticker "GOOG" (or any other symbol for that matter), I get the an empty list along with the following error:

401 Client Error: Unauthorized for url: https://api.robinhood.com/fundamentals/?symbols=GOOG

Did something break? How come I'm unable to pull that information anymore?

**Comment by jmfernandes** [comment]
@Ali-Riaz Robinhood has been going down lately. I'd wait until Tomorrow or Tuesday and see if it is still happening.

**Comment by Ali-Riaz** [comment]
@jmfernandes Gotcha, thank you Joshua! Will try again tomorrow and let you know.

**Comment by Ali-Riaz** [comment]
@jmfernandes Its working fine now, closing the ticket.
