### ISSUE TITLE
Issue with accessing data on date of expiry for an option chain

### ISSUE THREAD

**Issue by AmeliorateOr** [jmfernandes/robin_stocks#17]
Hello jmfernandes,

I believe this is the issue I ran into a while back, but by the time we had discussed it, you suggested that the old chain had expired, as it had indeed and that was why it was unable to access said data. This was perfectly logical so I didn't think much of it after that.

Now however, I've been running this real-time today trying to access "2019-03-08" option data, and my file saves are [null]. The chain is active on Robinhood's end(I can access the data, on their site, etc.) but for some reason the code does not respond as expected and returns [null]. 

I get no errors on my end using your .api so I believe it must be a logic error of some sort within the code. The empty list infers that the function runs properly but the code does not execute as expected to be able to store the data as a dictionary in a list as you've made it do, so it instead returns an empty list with null, saving the [ null ] . I suspect you have a function that returns Null (for the dictionary methinks?), and this may be a great place to look at why it is returning null on a day of expiry, and only the date of expiry.

Also just to test this further, after running the save twice and getting a file saved with null in it, I changed the expirationDate from "2019-03-08" to "2019-03-15" and this worked like a charm. So this further confirms my suspicion. 

I have no idea if you're aware of this issue or not, but I thought I should at least mention it.

I've been learning more, but I don't think I'm capable of debugging such a large project, but I'll attempt to read through the lines and see if I catch anything. I suspect some of this will definitely beyond my level of understanding. I'm hoping you can find it though as not having that last day of data is very detrimental to being able to review a full week of data from start to finish.

**Comment by AmeliorateOr** [comment]
After reviewing the source, I kept seeing the 'rhs_tradability : tradable' check. This leads me to consider the idea that since on Friday(expiry date) you're only able to enter closing positions, this might cause the rhs_tradability to be untradable. 

I don't know how to verify this, but I thought it was worth a mention, and something important to consider for getting this data on expiry dates if that was in fact the case.

**Comment by AmeliorateOr** [comment]
Here is an update:

So I discovered that there is something a little deeper in this, but I'm not sure how this applies to getting the data per se. I had an option that expired today that was purchased earlier this week. On the options expiry date, today, the option chain data does not show on Robinhood's end as I had originally thought it did. A mistake I made, because the options data does still show just not how I thought. 

To be more clear, the options data for the particular option I was holding was still updating live in the robinhood app. But a user is unable to view it unless an open position exists on that date, and only for that particular contract. I'm not sure how/why this would affect how I could pull this data, but it appears to be making it unavailable and I'll be trying to discover how to get around it still.

This makes some sense as Robinhood states that you can not open an option position on expiry dates, but I don't understand why you still can't view the data unless you have an active position(for just that specific contract -- not the entire chain)? It is being somehow altered, but it is still somewhere in there, hiding!

**Comment by AmeliorateOr** [comment]
In your options.py file, in lines 137-143 you have:

`except AttributeError as message:
        print(message)
        return [None]

    allOptions = find_tradable_options_for_stock(symbol,optionType)
    filteredOptions = [item for item in allOptions if item["expiration_date"] == expirationDate
                        and item['rhs_tradability'] == 'tradable']`

This is likely the return [None] list that I'm getting when I run this on an expiry Friday, but for the rhs_tradability'] == 'tradable . The item is not tradable on Friday, so how does one get that data on Friday? 

I'm stuck at the moment don't know where to go from here.

**Comment by jmfernandes** [comment]
I think you should call the find_tradable_options_for_stock directly. This will give you all the available options for a stock, and you will have to filter them yourself to find what you want.

In the find by expiration and find by strike functions, i had to include the check for 'rhs_tradability' because when i was trying to update the market data, I was getting an error. But yeah the reason why you can't get the data on the day of expiration is because of the 'rhs_tradability' check.

**Comment by AmeliorateOr** [comment]
Perfect! 

I was having issue at first getting an error saying: module robin_stocks doesn't have the attribute find_tradable_options_for_stock. I quickly realized I needed to get the most recent package upgrade for robin_stocks. Ran smoothly afterwards. 

I'll report back after I test this on Friday for expiring options data. Thanks for the suggestion.

**Comment by AmeliorateOr** [comment]
Doing a quick test just moments ago I find using the find_tradable_options_for_stock(..) still doesn't get the expiry date data. I just did a search in the file I saved and that expiration_date is nowhere to be found. I do enjoy this alternative being able to save the entire set of option data, but not having expiry is really detrimental to a proper backtest, etc. 

Do you know of any way to access the expiry day chain through Robinhood's .API using this wrapper?
