### ISSUE TITLE
Disabling stdout

### ISSUE THREAD

**Issue by toddpi314** [jmfernandes/robin_stocks#184]
On `robin-stocks==1.5.2`, attempted:
```
import robin_stocks.helper as helper
helper.set_output(None)
// Do stuff
```

But, still seeing stdout statements.

What is the best way to disable those stdout logs?

ref: https://github.com/jmfernandes/robin_stocks/pull/163

**Comment by jmfernandes** [comment]
helper.set_output(open(os.devnull,"w"))

works for me
