### ISSUE TITLE
percent_change float division by zero

### ISSUE THREAD

**Issue by scrivenerb** [jmfernandes/robin_stocks#2]
running the basic starting code:
```
from robin_stocks import robin_stocks
r = robin_stocks()
login = r.login('<myemail>','<mypassword>')
my_stocks = r.build_holdings()
```

returns the following error

> line 4, in <module>
>     my_stocks = r.build_holdings()

> "__init__.py", line 921, in build_holdings
>     percent_change  = (float(price)-float(item['average_buy_price']))*100/float(item['average_buy_price'])
> ZeroDivisionError: float division by zero

**Comment by dallasspohn** [comment]
Do you have any robinhood stocks to populate the field?

**Comment by scrivenerb** [comment]
Yeah I have several.

**Comment by scrivenerb** [comment]
Also I think the logout endpoint may have changed. I'm getting a 404 on that.

**Comment by scrivenerb** [comment]
If i comment out the percent_change lines then build_holdings runs fine btw.

**Comment by jmfernandes** [comment]
Thanks for the comments. These issues should be fixed now. I've found some additional problems. The  get_international_profile and get_employment_profile return 404's. I know they worked at one point so Robinhood must have changed or deleted the endpoints. If they no longer exist then I will delete them from my code, but I still need to find out. 

also, There is something wrong with the functions that have to deal with getting a list of orders. looking into this as well.
