### ISSUE TITLE
Website Documentation Missing

### ISSUE THREAD

**Issue by timtobey** [jmfernandes/robin_stocks#21]
The following documentation is not visible on the  Robin Stocks website:
Getting Positions and Account Information
Placing and Cancelling Orders

**Comment by jmfernandes** [comment]
I go into some detail here http://www.robin-stocks.com/en/latest/quickstart.html Should the documentation be more detailed?

**Comment by timtobey** [comment]
look at the section  :
List of All Functions

As you might know,  in this section these items are not documented. I would document them in the same manner as the other functions detailed; or at least redirect them to the quick start.  
Thanks I have found your library helpful!

**Comment by jmfernandes** [comment]
ah, i believe its because i started using decorators for those functions. I automatically generate the docs using Sphinx. I'll look into this. thanks.

**Comment by jmfernandes** [comment]
fixed.
