### ISSUE TITLE
Disabling "Loading page" message printing

### ISSUE THREAD

**Issue by nabelekt** [jmfernandes/robin_stocks#222]
I am trying to figure out how to disable the printing that looks like:
```
Found Additional pages.
Loading page 2 ...
Loading page 3 ...
Loading page 4 ...
Loading page 5 ...
Loading page 6 ...
```
when I fetch order information in [my project](https://github.com/nabelekt/robinhood_api).

@jmfernandes, would you accept a pull request that removes lines 307, 308, and 317 from [helper.py](https://github.com/jmfernandes/robin_stocks/blob/master/robin_stocks/helper.py)?

Alternatively, an optional `verbose` argument could be passed in to `robin_stocks.orders.find_stock_orders()` and other functions and passed down the line to `reqeust_get()` [(here)](https://github.com/jmfernandes/robin_stocks/blob/master/robin_stocks/helper.py#L258) to allow for something like `if verbose:`.  If that were done, the `verbose` argument should probably apply to other print statements too, but I'm not sure that I want to sign up to do that work.

Thanks for the great module!

**Comment by benpete22** [comment]
I too am having this issue. 
I tried redirecting stdout like this [https://stackoverflow.com/a/45669280](https://stackoverflow.com/a/45669280
) but this message is still able to print.

**Comment by nabelekt** [comment]
I too tried redirecting `stdout`, redifining `print`, etc., but didn't have any luck.

**Comment by nbr23** [comment]
you can set the output to stdout (or stderr):
```python
import robin_stocks
robin_stocks.helper.set_output(open(os.devnull,"w"))
```
And this should affect all prints. Tested and validated with find_stock_orders.

**Comment by nabelekt** [comment]
@nbr23's solution worked for me. Thanks!

**Comment by mw66** [comment]
Even this solution works, I still think we should have an optional verbose argument. @jmfernandes
