### ISSUE TITLE
Order Sell Stop Loss: Error - stopPrice must be above the current price

### ISSUE THREAD

**Issue by timtobey** [jmfernandes/robin_stocks#23]
Placing r.order_sell_stop_loss  with a stop price lower than current market price creates the following error:
Error: stopPrice must be above the current price

To recreate error :
      ZNGA Current price is $5.58

 r.order_sell_stop_loss(symbol='ZNGA', quantity= 1,  stopPrice= 5.25, timeInForce='gtc')

Here is stop order definition from Robinhood to make sure there is no confusion:

_A stop order is an order type that triggers a market order to buy or sell when the stock reaches your designated stop price. For example, if XYZ stock is trading at $25, you can place a sell stop order at $20 to trigger a market sell order in the event the stock reaches $20 or lower._

Given this the  stop price  should below the current market price not above,

The code appears to be the same for order_sell_stop_limit which should also use a stop price lower than current market  price.

**Comment by jmfernandes** [comment]
whoops. looks like i forgot to change the comparison operator from buy to sell. will update on github. you can pull the changes and then run "pip install ." in terminal.

in the mean time, you can use order()

**Comment by timtobey** [comment]
Hey, No good deed goes unpunished!
Thanks.
