### ISSUE TITLE
get_bank_transfers() not working

### ISSUE THREAD

**Issue by jimmy-cwu** [jmfernandes/robin_stocks#231]
When `https://api.robinhood.com/ach/transfers/` called returns `502 Server Error: Bad Gateway for url: https://api.robinhood.com/ach/transfers/`

**Comment by nbr23** [comment]
works fine for me, did you try again? I believe Robinhood had some hiccups this week, so perhaps you tried at a bad time.

**Comment by jimmy-cwu** [comment]
You are right, it was hiccups from Robinhood server
