### ISSUE TITLE
r.get_stock_historicals returning only times between 3pm and 8pm

### ISSUE THREAD

**Issue by Daktic** [jmfernandes/robin_stocks#241]
When calling the get_stock_historicals function, I am only returning between times between 15:00 and 20:00.
and example of the timestamp range below:
2021-02-11T15:00:00Z
and
2021-02-11T20:00:00Z

I am calling the function like so: r.get_stock_historicals(stock, interval='hour', span=''week'

**Comment by maconard** [comment]
I can't reproduce this. Such a call returns all necessary datapoints. Here is a graph I just made using the results from "hour" and "week" for AMD on that API call.

![image](https://user-images.githubusercontent.com/31703304/109187066-8c0a0f00-775f-11eb-9a21-bb980faccb1f.png)
