### ISSUE TITLE
Cannot import robin_stocks

### ISSUE THREAD

**Issue by therahulmanocha** [jmfernandes/robin_stocks#249]
Getting this ERROR while importing robin_stocks into python
import robin_stocks as rh

**/usr/local/lib/python3.6/dist-packages/robin_stocks/robinhood/account.py in <module>()
      3 from uuid import uuid4
      4 
----> 5 import robin_stocks.robinhood.helper as helper
      6 import robin_stocks.robinhood.profiles as profiles
      7 import robin_stocks.robinhood.stocks as stocks

AttributeError: module 'robin_stocks' has no attribute 'robinhood'**

**Comment by jskrainka** [comment]
I'm also getting this error, mac OS Catalina. Tried to install through source code and pip

**Comment by therahulmanocha** [comment]
1. I am using Google Collaboratory. The import was working till yesterday morning but stopped working by evening. Not sure what happened.
2. Also I have MacOS Big Sur and i tried install using "pip install", which works, but i get this error on import: 
'ModuleNotFoundError: No module named 'requests'. So i tried installing "requests" module using pip, which works, but i still can't import "requests" module. I still get this error "ModuleNotFoundError: No module named 'requests'"

**Comment by ncolella-mghpcc** [comment]
Yup, 2.0.0 is broken. Same error.

**Comment by therahulmanocha** [comment]
How do we know if someone is fixing this issue?

**Comment by seriousssam** [comment]
Same issue on Colab and my local Windows machine. Something broke. I hope we can get the devs attention.

**Comment by randallscott25** [comment]
Same Issue and on Collab. What is the ETA for addressing, please?

**Comment by jmfernandes** [comment]
Have you tried changing your import statement to

Import robin_stocks.robinhood as rh?

**Comment by cstampar** [comment]
Same issue on Colab. Have also tried "import robin_stocks.robinhood as rh" and also produces the same error.

**Comment by ncolella-mghpcc** [comment]
> Have you tried changing your import statement to
> 
> Import robin_stocks.robinhood as rh?

Yes.

**Comment by jmfernandes** [comment]
Hmm, yeah it looks like the import statements were broken for Google collab. I was getting same error.

Try out version 2.0.2. Just tested myself on Google collab and it worked for me.

**Comment by therahulmanocha** [comment]
It works now! Thanks
