### ISSUE TITLE
get_crypto_quote returns no volume

### ISSUE THREAD

**Issue by dgabriele** [jmfernandes/robin_stocks#263]
The "volume" field in the return value of `get_crypto_quote` is always 0.000000? I'm not familiar with the Robinhood API or what I should expect. If this is normal, please disregard. I would expect a non-zero value at least once in awhile, no? Thanks!

**Comment by Vampirebat** [comment]
Im having the same issue... even when i just try to get the volume by iteself.

**Comment by cheekylions** [comment]
I'm finding no evidence that Volume is part of Robinhood's Crypto datastream. You may have to find an alternate source for volume if you need it.

**Comment by dgabriele** [comment]
Yeah, it's Robinhood. Even their own app shows "Volume: 0" for cryptos.
