### ISSUE TITLE
Support Crypto-Currencies

### ISSUE THREAD

**Issue by jakobzhao** [jmfernandes/robin_stocks#27]
Robinhood has supported Bitcoin and Ethereum for a while. It would be great if robin_stocks can support bitcoin or other cryptocurrencies.

**Comment by Ericdataplus** [comment]
i too second that

**Comment by ChuckHend** [comment]
I started looking at this last night.

```
robin_stocks.order_buy_crypto_by_price(
    symbol='btc',
    amountInDollars=1
)
```
This is returning `None` and `400 Client Error: Bad Request for url: https://nummus.robinhood.com/orders/` is getting printed to console.

**Comment by jmfernandes** [comment]
This code is part of main branch now.
