### ISSUE TITLE
Robinhood pickle file not saving authentication

### ISSUE THREAD

**Issue by nickdela** [jmfernandes/robin_stocks#301]
Robinhood.authentication.login() always throws the error ERROR: There was an issue loading pickle file. Authentication may be expired - logging in normally.

**Comment by nickdela** [comment]
pickle authentication storage not working

Push #300 suggests the device token is always changing 

I installed push #300 “fix the ever changing…” which seems related but the error remains

Users also noted correctly every login creates a new Robinhood device

Users also noted correctly Pickle file has strange characters in it

tested on macOS and Linux

**Comment by nickdela** [comment]
Closed issue #296 seems to be the exact same issue. Not sure why it was closed

**Comment by bgridley** [comment]
I resolved this error by changing robinhood/authentication.py at this line

```
res = helper.request_get(
                        urls.portfolio_profile(), 'regular', payload, jsonify_data=False)
```
to this
```
res = helper.request_get(
                        urls.portfolio_profile(), 'regular', jsonify_data=False)
```

The request shouldn't be sending a payload in a get request anyway, in doing so it adds the username and password to the URL as parameters. This is insecure. This change is much more secure as it will no longer send the username and password in the get request url as parameters, and simply checks if the session is still valid, without sending the information and fixes the "ERROR: There was an issue loading the pickle file"

**Comment by nickdela** [comment]
Works, thanks. You should submit a push. @jmfernandes

**Comment by bfoz** [comment]
@bgridley Are you going to submit a PR for this? If not, can I add it to #300?
