### ISSUE TITLE
Any plans to support getting the new data thats available via robinhood gold

### ISSUE THREAD

**Issue by Wheaties466** [jmfernandes/robin_stocks#31]
Like the title says it sounds like you are able to get order fill information on stocks. It would be nice to be able to get that and possibly put it in a nosql db.

**Comment by jmfernandes** [comment]
@Wheaties466 what exactly is the information that is available through robinhood Gold? Sorry for late reply :/

**Comment by jmfernandes** [comment]
This code is included in main branch now.
