### ISSUE TITLE
Question about logging in 

### ISSUE THREAD

**Issue by Chaneriel** [jmfernandes/robin_stocks#317]
Is there any way to run my bot for days without having to log back in. As far as I'm aware, the longest the program can stay logged in is a day. Also the by_sms=(true/false) doesnt work for me. I get an error if its false so that means I have to input a code every day which is inconveniencing. Is there any way to make the program just stay logged in until I turn it off, across several days

**Comment by fjehlik** [comment]
@Chaneriel, here is what I do that allows you to stay logged in:

login = rs.login(username='username'],
          password='password',
          expiresIn=86400*10,     # 86400s = 1day
          by_sms=True,
          store_session=True)

The 'expiresIn' variable is the number of seconds in a day. In my case I multiply that by 10 to get 10 days. It seems to log me out after a week so there may be a limit, however, you can certainly get a week. Most likely you have that variable not set and the default is 86400 seconds (one day).

**Comment by Chaneriel** [comment]
@fjehlik I have one more question if u dont mind. Do u have any clue why my sells executed through the API arent going through. I've tried selling more and less than I own and neither work. Also I'm selling by price not amount

![image_2021-09-18_102355](https://user-images.githubusercontent.com/88423729/133892045-55973795-2fe7-4303-9686-00afc1e55a59.png)
