### ISSUE TITLE
 import robin_stocks.module as module ModuleNotFoundError: No module named 'robin_stocks'

### ISSUE THREAD

**Issue by frediogo** [jmfernandes/robin_stocks#353]
I installed robin_stocks using: (pip install robin_stocks) but when I try to import it gives me an error. :(

I am importing as:

import robin_stocks as rh

Thanks!

**Comment by GrahamboJangles** [comment]
run `pip install robin_stocks` in your command prompt.

**Comment by frediogo** [comment]
I did that but didn't work. 

The problem is fixed now. Turns out Anaconda path was conflicting with Robin stocks. I had to remove Anaconda. Everything is working now.
