### ISSUE TITLE
New Crypto Statements Download

### ISSUE THREAD

**Issue by Adelantado** [jmfernandes/robin_stocks#364]
Hi everyone, Hope all is well. 

This past Summer Robin added new Crypto Account Statements;  I can get the Brokerage Account ones,  but not these ones.

Anyone knows the function needed to be able to download them ??   Thanks

![C Statements](https://user-images.githubusercontent.com/86815170/212559934-21d6a9e8-9784-4672-89ed-a336ca7e2abd.png)

**Comment by Adelantado** [comment]
:)

**Comment by themarkwilliams** [comment]
Hi, I see this issue is closed. . .did you figure out how to download the crypto statements? 

If so, could you please share your approach?
