### ISSUE TITLE
buy_fractional_by_price   ( order not even acknowledged by Robinhood ) 

### ISSUE THREAD

**Issue by Adelantado** [jmfernandes/robin_stocks#383]
Has happened a few times now and I can't figure what may be the problem.
Just yesterday my script run from beginning to end with no issues ( errors, halts, etc ) and placed two different buy_fractional_by_price stock orders but they did not go thru. 
My puzzle is: Orders were not rejected nor did fail, in addition, I got absolutely no feedback/response from Robinhood as if or why something went wrong; they just simply did not go thru nor registered as being placed to begin with. When looking at my orders history, there is no record that were placed at all ....  just like it didn't happen. FYI: these orders are based on a % of the account's available buying power so funds were def. available; we can rule that one out.
What will cause a "buy_fractional_by_price", which basically is a market order, not only NOT to be processed, but to be completely ignored to the point that is not even a record of it in your history ?
Was wondering if someone is experiencing this issue or can provide some kind of suggestion as what may cause this kind of behavior.
Thanks.

**Comment by JaydenLong-Pseudo-SamCole** [comment]
Go to the previous thread m8

**Comment by Adelantado** [comment]
Thanks. I did read about it after I posted and installed version 3.0.1, but to be honest, I am still not sure if that will help / fix the issue.  My script runs 24/7 for crypto, but that specific routine only runs about 10 minutes from market close on trading days, so all I can do is wait n see till Tuesday or till conditions trigger the buy by fraction on one of the stocks on my list during a trading day.    On Saturday, May 27, 2023 at 03:15:22 PM EDT, JaydenLong-Pseudo-SamCole ***@***.***> wrote:  
 
 


Go to the previous thread m8

**Comment by Adelantado** [comment]
Thanks. I did read about it after I posted and installed version 3.0.1, but to be honest, I am still not sure if that will help / fix the issue.  My script runs 24/7 for crypto, but that specific routine only runs about 10 minutes from market close on trading days, so all I can do is wait n see till Tuesday or till conditions trigger the buy by fraction on one of the stocks on my list during a trading day.

**Comment by Adelantado** [comment]
Still out of luck. I can place fractional sells but no buys. Sells are placed and filled entered as:
robin_stocks.robinhood.orders.order_sell_fractional_by_price(item, float(amount), timeInForce='gfd', extendedHours=False)

Buys placed were not even acknowledged:
robin_stocks.robinhood.orders.order_buy_fractional_by_price(item, float(mount), timeInForce='gfd', extendedHours=False)

Any thoughts would be greatly appreciated. Thanks.

**Comment by Adelantado** [comment]
I did play around with GuitarGuyChrisB fixes but no luck.  Buy_Fractional keeps getting completely ignored or throws error:
Error in request_post: Expecting value: line 1 column 1 (char 0).

Any guidance would be greatly appreciated. Thanks.

**Comment by Adelantado** [comment]
All good now, thanks.

**Comment by Adelantado** [comment]
All good now; hopefully one of these days I will finally learn how to cut n pasted LOL.
