### ISSUE TITLE
NEW ... Robinhood Crypto Customer Agreement and API use

### ISSUE THREAD

**Issue by Adelantado** [jmfernandes/robin_stocks#398]
Not really an issue but it could lead to one down the road. While reading over the new agreement I came across this:

19. API. I agree to access my RHC Account only through the Robinhood Platform. Any other use is not authorized, and I agree to refrain from using any application programing interface belonging to RHC or any of its Affiliates. 

Wondering if this is here just cause it has to be included from a legal perspective,  or if it has something to do with a merge or acquisition by a bigger fish. Saying that cause all the orders being slowly transitioned to a new format. 
Unsure if I am adding 2+2  or mixing apples and oranges in here. Again, just wondering.

**Comment by mobeston** [comment]
Thanks for bringing this up, at least the rest of us can know of this. Appreciate it!!

**Comment by Adelantado** [comment]
Whaaaaa!
