### ISSUE TITLE
Documentation of methods incomplete

### ISSUE THREAD

**Issue by nkaliape** [jmfernandes/robin_stocks#4]
There are certain copy-paste issues in the documentation

**Comment by jmfernandes** [comment]
I see that I forgot to change the type parameter to OptionType. Did I miss anything else?

Also, I'm currently working on breaking up the code into several modules to make it easier to find functions and I'm going to replace the README documentation with Sphinx documentation on its own webpage. Things will be a lot more streamlined when that happens.
