### ISSUE TITLE
What happened to the API docs?

### ISSUE THREAD

**Issue by TKassis** [jmfernandes/robin_stocks#400]
Thanks to everyone who contributes to this incredible API.

I was wondering what happened to the official API docs here:

https://robin-stocks.readthedocs.io/en/latest/robinhood.html#

I remember using them a year or so ago.

**Comment by jmfernandes** [comment]
@TKassis  should be fixed now. If the webpage ins't loading for you. Hold down the shift key while you click the "reload page" button

**Comment by TKassis** [comment]
Works! And thanks for this excellent repo!
