### ISSUE TITLE
404 Client Error: Not Found for url:

### ISSUE THREAD

**Issue by Adelantado** [jmfernandes/robin_stocks#406]
I've been getting errors for hours when requesting fundamentals and quotes on regular stocks like AAPL or AMD

404 Client Error: Not Found for url: https://api.robinhood.com/fundamentals/?symbols=AMD
404 Client Error: Not Found for url: https://api.robinhood.com/quotes/?symbols=AMD 

Is anybody experiencing this ?  Are servers down or are these functions no longer valid ??

Thanks

**Comment by SingularityMan** [comment]
Same here. Just happened today. Not sure what is going on this time.

**Comment by eilin75** [comment]
I also have the same problem

**Comment by eilin75** [comment]
It seems to be working again.

**Comment by SingularityMan** [comment]
> 

Same. It works now.

**Comment by W-M-D** [comment]
oh annoying

**Comment by Adelantado** [comment]
Seems we did survive this one and we'll live to fight another day. GLT Yall.

**Comment by richik-p** [comment]
APPL does not work even now :(
