### ISSUE TITLE
Missing function for viewing crypto holdings

### ISSUE THREAD

**Issue by gldstrrbt** [jmfernandes/robin_stocks#41]
I can't seem to find the method for requesting crypto holdings or USD valuations of crypto holdings. I've tried ever method available, but none return crypto. Am I missing something?

**Comment by gldstrrbt** [comment]
Found the endpoint and have integrated it as needed. 

In case anyone else is having the same issue:
https://nummus.robinhood.com/holdings/

**Comment by jmfernandes** [comment]
Could you do me a favor and do a pull request?
