### ISSUE TITLE
Enhancement: Options "sell_to_open", "buy_to_close" orders

### ISSUE THREAD

**Issue by nkaliape** [jmfernandes/robin_stocks#43]
This is to do handle options order variant.

**Comment by jmfernandes** [comment]
What is the issue? I'm a little confused.

**Comment by nkaliape** [comment]
today we have buy and sell - in which
buy - you can open fresh position
sell - you can sell only existing position..

There is other case:
where you can (short) sell the option
and cover those open short positions.

Will create API for the same and send merge req.

Thanks,
Narayan

**Comment by eliezerp3** [comment]
Hey man. Same problem here. Did you find a solution?

**Comment by jmfernandes** [comment]
fixed. see comment in #83
