### ISSUE TITLE
Invalid Bearer Token - Unable to load pickle file

### ISSUE THREAD

**Issue by lukeganzevoort** [jmfernandes/robin_stocks#44]
I was able to login successfully previously, but today when I tried to login I got the following error. I was able to get around this by deleting the `site-packages/robin_stocks/data.pickle` file and then re-authenticating my computer.

```
ERROR: There was an issue loading pickle file - logging in normally.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "get_stocks.py", line 11, in <module>
    login = robin_stocks.login(user, passwd)
  File "/home/myusr/.local/lib/python3.6/site-packages/robin_stocks/authentication.py", line 142, in login
    raise Exception(data['detail'])
Exception: Invalid bearer token.
```

**Comment by jmfernandes** [comment]
Yeah I was getting that error too but inconsistently. I think I need to do something with the refresh token.

Also to get around issue you can call login(username,password,store_session=false) setting store session to false auto deletes pickle file.

**Comment by seriousssam** [comment]
I am getting the same error at the moment from 2 different accounts.

The fix above from jmfernandes doesn't seem to work anymore: when I set store_session=false, I still get the error on the next login (with store_session=True) but it logs in without asking me for sms code.

BUT the next time I log in after that, it asks for the code again.

**Comment by mattcar15** [comment]
I am getting the same issue. It asks for the code every time or it throws this error. Should I open a new ticket for this?

**Comment by bfoz** [comment]
This may be related to #300
