### ISSUE TITLE
Close entire position

### ISSUE THREAD

**Issue by meldinman** [jmfernandes/robin_stocks#445]
This is more of a discussion/question than an issue but I don't see a discussion tab in this repo.
Whenever I try exiting an exisiting stock position I can never get the full position closed. Whether I use close by quantity or notional, I am always left with a residual position on. Has anyone figured out how to fully close out a position without having to manually login?

**Comment by Adelantado** [comment]
Had that issue till I switched to : order_sell_fractional_by_quantity. Hope it helps.

**Comment by meldinman** [comment]
you are correct. I was using `order_sell_fractional_by_quantity` but after looking into my code it seems I was rounding the quantity downstream. Probably because of the 6 decimal point constraint when doing notional. All fixed now!
