### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by jmyers350** [jmfernandes/robin_stocks#45]
Attempted to install via pip - 
![image](https://user-images.githubusercontent.com/55290158/64883402-e58e8480-d624-11e9-9058-b103821d3862.png)

**Comment by jmmadsen** [comment]
I am having this same issue - does anyone know what is going wrong?

**Comment by jmfernandes** [comment]
@jmmadsen you need to use python 3 and not python 2.

**Comment by jmmadsen** [comment]
Thanks for your quick reply. How do I use the pip install command with
python3 instead of python? I am on OS_X.
