### ISSUE TITLE
account.get_current_positions() doesn't return option positions

### ISSUE THREAD

**Issue by nick-martin-24** [jmfernandes/robin_stocks#46]
The following is used to return current positions, and per the function comments should "return stocks/options currently held":
`    url = urls.positions()
    payload = { 'nonzero' : 'true'}
    data = helper.request_get(url,'pagination',payload)
`

I believe this will effectively return the data from 'https://api.robinhood.com/positions/?nonzero=true'. I currently only hold options in my robinhood account (no stocks), and account.get_current_positions() returns an empty list ([]).

I'm not sure if the intent is to include options as well, so if not the comment could just be modified to just call out stocks. I haven't yet been able to find a comprehensive current stock+option list.

**Comment by jmfernandes** [comment]
get_all_option_positions(info=None) should return option positions but it seems to be a but buggy and doesnt return everything. (Theres also one for crypto positions in crypto.py)

I should include this info in readme because its confusing why robinhood has it split up on their API but all history is in a single display on their website/app

**Comment by nick-martin-24** [comment]
agreed....would be nice to access all at once. Although in my scenario I only need to access one type.

Really cool library, I like what you've done and glad I stumbled upon this

**Comment by alexonab** [comment]
Not exactly the same issue but kind of related.  When no positions are open, it would be helpful if the return value is an empty list.  This makes it easier to tell if there are any positions vs the current response of [None] which is a single element list.

````
>>> len([]) == 0 
True
>>> len([None]) == 0 
False
````

Currently, I have to add an extra check to not try and process the current empty response.

````
        positions = r.get_open_option_positions()
        for pos in positions:
            if pos is None:
                continue
            print(f"{pos}")
````

**Comment by jmfernandes** [comment]
@alexonab great idea and would be easy for me to implement. All I have to do it edit helper.filter() which formats the data for all functions.

**Comment by jmfernandes** [comment]
@alexonab pull the latest code from github and install it and it should have the changes where the returned lists are [ ] instead of [None] so your if not list condition should execute properly now.
