### ISSUE TITLE
Robinhood ira

### ISSUE THREAD

**Issue by Thesyjaga** [jmfernandes/robin_stocks#472]
The new update says it supports ira but I cant code for ira. I want to make my code where it scans through all the accounts I have and it places a trade there.

My code rn

import sys
import os
import pyotp
from robin_stocks import robinhood
import time

KEY = "..."
EMAIL = "...."
PASSWD = "..."

def generate_otp(key):
    totp = pyotp.TOTP(key)
    return totp.now()

def login():
    otp = generate_otp(KEY)
    login_result = robinhood.login(EMAIL, PASSWD, mfa_code=otp)
    if login_result:
        print("Login successful!")
    else:
        print("Login failed.")
    return login_result

def logout():
    robinhood.logout()
    print("Logged out.")

def display_price(ticker):
    login()
    try:
        price = robinhood.stocks.get_latest_price(ticker)
        if price:
            print(f"{ticker.upper()}: ${price[0]}")
        else:
            print(f"Unable to retrieve price for {ticker}.")
    except Exception as e:
        print("Error:", e)
    finally:
        logout()

def SELL(ticker, quantity):
    try:
        login()
        r = robinhood.order_sell_market(ticker, quantity, timeInForce='gfd') 
        print(r)
        time.sleep(10)  
    except Exception as e:
        print("Error selling:", e)
    finally:
        logout()

def BUY(ticker, amount):
    try:
        login()
        r = robinhood.order_buy_market(ticker, amount)
        print(r)
    except Exception as e:
        print("Error buying:", e)
    finally:
        logout()

def main():
    TICKER = sys.argv[1:][0].upper()
    display_price(TICKER)

    if len(sys.argv[1:]) > 2:
        ACTION = sys.argv[1:][1]
        AMOUNT = sys.argv[1:][2]
        if ACTION.upper() == "BUY":
            print("Buying " + AMOUNT + " of " + TICKER + "...")
            BUY(TICKER, AMOUNT)
        if ACTION.upper() == "SELL":
            print("Selling " + AMOUNT + " of " + TICKER + "...")
            SELL(TICKER, AMOUNT)

    time.sleep(3) 

 
    input("Press Enter to exit...")

if __name__ == "__main__":
    main()

**Comment by Thesyjaga** [comment]
In the new update I am soo confused I dont know how to get all the account ids and place them in all

**Comment by NelsonDane** [comment]
Hi, it's me, just chiming in. The default for `load_account_profile()` is to only return the first account, which I didn't change at all (as to not break anyone's current programs). What I did and what was later merged was to add an argument to return more info (IRA accounts). Call the function with `load_account_profile(dataType="results")` and it should include all account results, instead of the default of `indexzero` (first account only). @Thesyjaga @doctorcolossus

**Comment by NelsonDane** [comment]
Yeah, you're right, what I wrote isn't very clear at all without seeing the original data. A new function would be great, such as a `get_all_account_numbers()`. Maybe someone can make a PR for the new function and change my comment to something more clear 😆

**Comment by Thesyjaga** [comment]
I was busy I just tried the code and it works!
