### ISSUE TITLE
Sell Market Orders do not work (but Buy Market Orders Work)

### ISSUE THREAD

**Issue by ChewyCorndog** [jmfernandes/robin_stocks#474]
The robinhood function order_sell_market(ticker, amount) is giving me an error. I am trying to sell 1 share of my stock, but it doesn’t not go through. The buy and quote functions have been working, so I’m hoping it’s something simple. Any suggestions are greatly appreciated!

**Comment by Thesyjaga** [comment]
can we see the code?

**Comment by ChewyCorndog** [comment]
> can we see the code?
`#!/usr/bin/python3.8
#backup for 2FA 177616 432276

import sys
import os

import pyotp
import robin_stocks as robin

lines = open('D:/info.txt').read().splitlines()
KEY = lines[0]
EMAIL = lines[1]
PASSWD = lines[2]
CODE = lines[3]
ACCOUNTNUM = int(lines[4])
totp = pyotp.TOTP(KEY).now()
print ("current otp:", totp)
login = robin.robinhood.authentication.login(EMAIL,PASSWD, mfa_code=totp)

def QUOTE(ticker):
    r = robin.robinhood.stocks.get_latest_price(ticker)
    print(ticker.upper() + ": $" + str(r[0]))
    return r[0]

def SELL(ticker, ammount):#does not work
    limit = QUOTE(ticker)
    r = robin.robinhood.orders.order_sell_market(ticker,ammount)
    #limitprice =  QUOTE(ticker)
    #r =  robin.robinhood.orders.order_sell_limit(ticker,ammount,4.22)  #order_buy_market(ticker,ammount)
    print(r)

def BUY(ticker, ammount):
    r = robin.robinhood.orders.order_buy_market(ticker,ammount)
    print(r)

def BUYCRYPTO(ticker,amount):
    r = robin.robinhood.orders.order_buy_crypto_by_price(ticker, amount)
    print(r)
    return r
def SELLCRYPTO(ticker,amount):
    r = robin.robinhood.orders.order_sell_crypto_by_price(ticker, amount)
    print(r)    

def SELLCRYPTOBYSHARES(ticker,amount):
    r = robin.robinhood.orders.order_sell_crypto_by_quantity(ticker, amount)
    print(r)
def GETCRYPTOHOLDINGS():
    r = robin.robinhood.crypto.get_crypto_positions()
    print(r)
    return r
def CRYPTOQUOTE(ticker):
    r = robin.robinhood.crypto.get_crypto_quote(ticker)
    return r
def GETOPENPOSITIONS():
    r = robin.robinhood.account.get_open_stock_positions()
    print(r)
    return r
if len(sys.argv[1:]) > 2:
    ACTION = sys.argv[1:][0]
    TICKER = sys.argv[1:][1].upper()
    AMOUNT = sys.argv[1:][2]
    if ACTION.upper() == "BUY":
        print("Buying " + AMOUNT + " of " + TICKER + "...")
        BUY(TICKER, AMOUNT)
    if ACTION.upper() == "SELL":
        print("Selling " + AMOUNT + " of " + TICKER + "...")
        SELL(TICKER, AMOUNT)
    if ACTION.upper() == "QUOTE":
        QUOTE(TICKER)
    if ACTION.upper() == "BUYCRYPTO":
        BUYCRYPTO(TICKER, AMOUNT)
    if ACTION.upper() == "SELLCRYPTO":
        SELLCRYPTO(TICKER, AMOUNT)
    if ACTION.upper() == "GETCRYPTOHOLDINGS":
        GETCRYPTOHOLDINGS()
    if ACTION.upper() == "GETOPENPOSITIONS":
        GETOPENPOSITIONS()`

**Comment by Thesyjaga** [comment]
you copied the guy from the vid.

Now instead of import "robin_stocks as robin" its "import robin_stocks as robinhood" your not even using the robinhood library thats why

**Comment by ChewyCorndog** [comment]
I did use the code from a youtube video as an starting point, but my import statement is not the problem. It just means that I refer to robin_stocks as "robin" in my code instead of as "robinhood". I have been successfully using the library to buy and quote stocks. But selling has not worked for me.

**Comment by Thesyjaga** [comment]
this is how mine looks


def SELL(ticker, quantity):
    account_numbers = get_all_account_numbers()
    for account_number in account_numbers:
        if login(EMAIL, PASSWD, KEY):
            try:
                r = rh.orders.order_sell_market(ticker, quantity, timeInForce='gfd')
                print(f"Sell order result: {r}")
                time.sleep(10)
            except Exception as e:
                print("Error selling:", e)
            finally:
                logout()

**Comment by ChewyCorndog** [comment]
adding the timeInForce parameter fixed my problem! Did not require that parameter for buying, but glad its working now.
