### ISSUE TITLE
Multi logins

### ISSUE THREAD

**Issue by Thesyjaga** [jmfernandes/robin_stocks#475]
I have 2 logins and I made a code in my first login but when I make another py file and use the same code but I did change my login creds to my second login and it is accessing my first login and placing it there how is this even possible?

**Comment by Adelantado** [comment]
See #396, hope it helps.

**Comment by Thesyjaga** [comment]
this is the method I did. I used "import atexit" and with that what i did is make the first login go through then the atexit would delete the robinhood.pickle file as mentinoed above and then when it goes through second login it automatically makes an pickle file and therefore after that finshes up it would also delete that.

**Comment by Thesyjaga** [comment]
this is the method I did. I used "import atexit" and with that what i did is make the first login go through then the atexit would delete the robinhood.pickle file as mentinoed above and then when it goes through second login it automatically makes an pickle file and therefore after that finshes up it would also delete that.
