### ISSUE TITLE
404 error on Get_Historicals()

### ISSUE THREAD

**Issue by codeinflash** [jmfernandes/robin_stocks#48]
I just tried: get_historicals('BTC')

I get an error:
404 Client Error: Not Found for url: https://api.robinhood.com/quotes/historicals/?symbols=BTC&interval=10minute&span=week&bounds=regular

get_historicals('FB') works fine though

**Comment by jmfernandes** [comment]
That function only applies to stocks. If you look at the documentation, you'll see that it is part of the stocks module.

http://www.robin-stocks.com/en/latest/functions.html#robin_stocks.stocks.get_historicals

Robin-stocks does not have a way to view the historical for crypto or option price historicals.
