### ISSUE TITLE
401 errors / can't log in / OTP issues ??

### ISSUE THREAD

**Issue by Adelantado** [jmfernandes/robin_stocks#509]
I just posted this as a response to #506, not the same issue however, something def is up with Robin servers. Has anything changed @ log in ??

Unsure if related but .....last Sunday around 2 -3 am I was experiencing 401 errors in the two accounts I run. I even got a new 2AF code for one of them thinking it had expired or whatever. Problem went away as fast as it came, however, today and since 4 pm NY time one of the accounts will not longer log in and neither of the two OTP scripts I have to log in via browser works. It has def something to do with the 2AF cause the code on those OTP scripts is basically 2 lines of code.

![Log in Crap](https://github.com/user-attachments/assets/fa5431d8-9ccd-4ceb-87a4-34d861200004)

**Comment by ravi-bharadwaj** [comment]
I am getting unsupported_grant_type errors with a status code 403(had to modify my fork to get the error codes)

**Comment by hokeihero** [comment]
I am no longer be able to login at all

**Comment by aLearningProcess** [comment]
Same issue. Happy to help  investigate, but not sure where to start.

**Comment by ravi-bharadwaj** [comment]
You can close this thread and hop on to issue#511

**Comment by Adelantado** [comment]
Thanks for all the Help!
