### ISSUE TITLE
I can't login via the API anymore, unexpected post response

### ISSUE THREAD

**Issue by jnasti10** [jmfernandes/robin_stocks#512]
Not sure what happened here. I login to my account everyday via the api and yesterday around noon PST it stopped working. 

I see this error:
  File "./main.py", line 26, in <module>
    login()
  File "/home/ec2-user/Misc/RHood/src2.0/utils/rhoodfuncs.py", line 12, in login
    login = r.login(values["USERNAME"], values["PASSWORD"], mfa_code=totp)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/robin_stocks/robinhood/authentication.py", line 193, in login
    raise Exception(data['detail'])
KeyError: 'detail'

I have debugged a bit and it seems like we are getting an unexpected response from the post req:
URL => https://api.robinhood.com/oauth2/token/
PAYLOAD => {'client_id': '******', 'expires_in': 86400, 'grant_type': 'password', 'password': '******', 'scope': 'internal', 'username': '********', 'challenge_type': 'sms', 'device_token': '********', 'mfa_code': '******'}
{
    "verification_workflow": {
        "id": "d7953e00-4f30-4a50-848f-f6646fd7be17",
        "workflow_status": "workflow_status_internal_pending"
    }
}

How do I fix this? I am still able to login manually with the same credentials.

**Comment by ahaggard2013** [comment]
If you have the time, I'd compare the request generated via the robinhood app to what is being sent by robin_stock. Something maybe slightly changed and could be updated in the library if that is the case. Check headers too, not just the payload data

**Comment by jnasti10** [comment]
How can I check this from the app?

**Comment by Gates8911** [comment]
Same issue, I use the default authentication code sent directly to robinhood app for sign in, so I always left the login request at default values other than changing the name of the token while using pc's environment variables to store login info to avoid hard coding. If anyone can help I would be greatly appreciative and even willing to share my strategies file with a bunch of custom indicators that handle robinhoods data, so far it has a 80%+ return in 3 months, needless to say i really need to get this working, im relatively new to coding, self taught, and desperately need to get my bot running again.

**Comment by Christopher-C-Robinson** [comment]
Try using #510. This worked for me.

**Comment by Gates8911** [comment]
Yup, I finally got it once i changed to otp login with 3rd party app, but i also had to add a few lines of code to ensure the session was actually updated, not sure why other than the pc i actually run my bot on it a bit dated now.
