### ISSUE TITLE
Support for New Robinhood Verification Workflow ("verification_workflow" key in login response)

### ISSUE THREAD

**Issue by Christopher-C-Robinson** [jmfernandes/robin_stocks#515]
When attempting to log in using `robin_stocks`, the authentication flow no longer provides the traditional "detail" key in the response. Instead, the API returns a JSON object containing a "verification_workflow" key with a "workflow_status" of "workflow_status_internal_pending". This suggests that Robinhood’s login process may now require an additional verification step that `robin_stocks` does not currently handle.

**Steps to Reproduce:**
1. Attempt to log in to Robinhood using `robin_stocks.authentication.login()` with TOTP-based MFA.
2. Instead of a successful login or a known error key, the response includes a JSON object like:
   {
     "verification_workflow": {
       "id": "some-uuid-value",
       "workflow_status": "workflow_status_internal_pending"
     }
   }
3. The login does not complete and no "access_token" is returned.

**Expected Behavior:**
- Previously, if MFA was correct and credentials were valid, the login would return an "access_token".
- If a challenge was required, a "detail" or "challenge" key guided the user to complete SMS/email verification.

**Actual Behavior:**
- The API now returns a "verification_workflow" object.
- No instructions or keys are provided to complete this new workflow.
- `robin_stocks` does not offer a method to handle this new verification process.

**Additional Details:**
- The "workflow_status" value "workflow_status_internal_pending" implies Robinhood requires an extra verification step.
- This issue persists after updating `robin_stocks` to the latest version.
- No "detail" key or standard challenge format is present.

**Proposed Solutions:**
1. Investigate the new verification steps that Robinhood expects for this `verification_workflow`.
2. Update `robin_stocks` to:
   - Recognize "verification_workflow" responses.
   - Provide a function or instructions to complete this workflow.
   - Document the new login flow and how users should respond.

**Request:**
- Please add support or documentation for handling the `verification_workflow` during the login process.
- Clarify what Robinhood expects from users to resolve "workflow_status_internal_pending" and allow programmatic logins to succeed.

**Comment by SumayKalra** [comment]
Having the exact same issue seem it is not possible to login because of this, even pushing the notification and allowing time for it does not work as it refuses to log in because of this extra verification step

**Comment by Christopher-C-Robinson** [comment]
This seems to do the trick for me. #510
