### ISSUE TITLE
Unable to login any more

### ISSUE THREAD

**Issue by aravindsvu** [jmfernandes/robin_stocks#519]
`data = request_post(url, payload)` doesn't seem to return `mfa_required` or `challenge` in the returned `data` anymore.

Did Robinhood add any new verification workflow?  The following is what we seem to be getting in the returned `data`.

`{'verification_workflow': {'id': 'abcdxxxx-yyyy-tttt-2222-7777ebec5555', 'workflow_status': 'workflow_status_internal_pending'}}`

Anyway to workaround this?

**Comment by vhrustic** [comment]
Same here

**Comment by Adelantado** [comment]
Take a look at #510. Hope it helps.

**Comment by p-o-f** [comment]
same issue

**Comment by aravindsvu** [comment]
Thank you @Adelantado . I dont really follow what needs to be done under the referenced ticket https://github.com/jmfernandes/robin_stocks/pull/510. I did take the `authentication.py` from https://github.com/jmfernandes/robin_stocks/issues/511#issuecomment-2524778713 and replace it as mentioned in there. Which moved my issue forward but I now fail in the `_validate_sherrif_id` method as below:

```
Traceback (most recent call last):
  File <snip>", line 143, in <module>
    login = rh.login(username=args.user, password=args.password, mfa_code=args.mfa, store_session=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>\venv\Lib\site-packages\robin_stocks\robinhood\authentication.py", line 190, in login
    _validate_sherrif_id(device_token=device_token, workflow_id=workflow_id, mfa_code=mfa_code)
  File "<snip>\venv\Lib\site-packages\robin_stocks\robinhood\authentication.py", line 230, in _validate_sherrif_id
    if challenge_response["status"] == "validated":
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'status'

```

A lot of the suggestions seem to be using `pyotp`, I already have a Google authenticator setup for app based MFA so didn't to use that. Prior to this issue the call to `login` used to prompt me for mfa which i would enter manually when I run the command. I no longer see mfa prompt and instead fail in the above. Any specific steps for my case?

**Comment by aravindsvu** [comment]
Just after typing the above, I tried running my script that calls `login()` but this time passing in the `mfa code` instead of leaving it out (set to `None`) to let the code prompt for it. That worked. 

I guess the problem is when calling POST https://api.robinhood.com/oauth2/token/ with `payload` that doesn't contain `mfa_code` key-value pair, the returned value does not set `mfa_required`. 

The fix in my case was just the first two steps in https://github.com/jmfernandes/robin_stocks/issues/511#issuecomment-2524778713 followed by supplying the mfa code as argument to the `login()` call.
