### ISSUE TITLE
Ethereum Classic transaction problems

### ISSUE THREAD

**Issue by jmyers350** [jmfernandes/robin_stocks#52]
Good Evening.

Found a potential bug.  All cryptos work except for buy/sell 'ETC'.  I was curious if anyone else is seeing this?

**Comment by jmfernandes** [comment]
What does the function return when you try to buy etc?

**Comment by jmyers350** [comment]
Regardless of the amount, it returns a price error.

**Comment by jmfernandes** [comment]
ah ok. This the same issue as #53 so im closing this issue. Post updates there, but for now i'll work on a fix.
