### ISSUE TITLE
selling crypto order always gives error "Order price has invalid increment."

### ISSUE THREAD

**Issue by codeinflash** [jmfernandes/robin_stocks#53]
Can you teach me how to set the selling price properly?

I also get the same error for the function: order_sell_crypto_by_quantity()

**Comment by jmyers350** [comment]
Which currency?

**Comment by jmfernandes** [comment]
What error are you getting? You dont give a price with order_sell_crypto_by_quantity

**Comment by codeinflash** [comment]
Error mesage is: Order price has invalid increment.
I found that if I edit the function itself in the robin_stocks.py price = round(price, 2), it works fine.
Maybe 8 decimal point is not allowed??
Please check it out!

Thanks!

**Comment by codeinflash** [comment]
both order by quantity and price not working if the price is 8 decimal places. Look at the inside of the definition

**Comment by jmfernandes** [comment]
which crypto? round(price, 2) does not work for doge coin because the price is so low that rounding to 2 decimal places give you zero. I probably need to make a new function that rounds based on the relative magnitude of the price.

**Comment by ericcastelli** [comment]
> Error mesage is: Order price has invalid increment.
> I found that if I edit the function itself in the robin_stocks.py price = round(price, 2), it works fine.
> Maybe 8 decimal point is not allowed??
> Please check it out!
> 
> Thanks!

Thanks for the tip!

**Comment by jmfernandes** [comment]
This should be fixed in the newest github version.

**Comment by kthulhu** [comment]
Experiencing the same issue with current version for any crypto other than BTC:
order_buy_crypto_by_price('BTC', 10.0) works fine, while
order_buy_crypto_by_price('ETH', 10.0) reporting '{'quantity': ['Order quantity has invalid increment.']}'
