### ISSUE TITLE
Prices above $1.00 can't have subpenny increments

### ISSUE THREAD

**Issue by bman393** [jmfernandes/robin_stocks#54]
Im running a simple program that buys/sells a given stock, and I keep getting the following error:
{'price': ["Prices above $1.00 can't have subpenny increments."]}

My program is as follows:
r.login('myUsername','myPassword')
print(r.order_buy_market('NIO',1,'gfd','true'))

would anyone know why this is happening?

**Comment by jmfernandes** [comment]
This should be fixed on the github version.

**Comment by bman393** [comment]
Thanks jmfernandes!

**Comment by ilyakatz** [comment]
@jmfernandes are you planning to push the version that has this fix to pip?

**Comment by jmfernandes** [comment]
@ilyakatz version 0.9.9.6 is now on pypi

**Comment by ilyakatz** [comment]
great, thanks @jmfernandes !

**Comment by giterdun345** [comment]
Not fixed yet on github or pip.
