### ISSUE TITLE
pep8 compliance to the code

### ISSUE THREAD

**Issue by shobnaren** [jmfernandes/robin_stocks#56]
https://www.python.org/dev/peps/pep-0008/ 

This is one of critical and must-have for better code readability.
There are few longer lines of code to modify / enhance  - makes it harder.
So, will make a pep8 using autopep8 and send it for review.

note: even variable naming needs to change: 
https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions [may be big challenge for code/app that rely on this library]

**Comment by jmfernandes** [comment]
Ok but do me a favor. Do one commit with the just the automatic pep formatting, and then a second commit with any miscellaneous changes. Try not to make any functional changes to code, even if you see something that needs fixing. Save that for another pull request
