### ISSUE TITLE
[bug] stopPrice should compare to the last regular hour price (instead of extended hour price)

### ISSUE THREAD

**Issue by mingwugmail** [jmfernandes/robin_stocks#64]
in func order_buy_stop_limit(), on line:
https://github.com/jmfernandes/robin_stocks/blob/e0c3febdda78a3310ac207a0a9ab9819624bc57a/robin_stocks/orders.py#L320
latestPrice = helper.round_price(stocks.get_latest_price(symbol)[0])
this returns the extended hour price.
and then it's used on line 328:
https://github.com/jmfernandes/robin_stocks/blob/e0c3febdda78a3310ac207a0a9ab9819624bc57a/robin_stocks/orders.py#L328

if (latestPrice > stopPrice):

When user calls this function during off-hours (e.g. at night for the next morning's order), it's comparing with the extended hour price, and the order will not be placed because of this client side check; but the user can actually place such order (as long as stopPrice > the_last_regular_hour_price) on the Robinhood website.

We should either refine this client side check to allow such order be placed, or we should remove this check and rely on the Robinhood server side check.

Same problem on order_buy_stop_loss() line 269 and 275
https://github.com/jmfernandes/robin_stocks/blob/e0c3febdda78a3310ac207a0a9ab9819624bc57a/robin_stocks/orders.py#L269
https://github.com/jmfernandes/robin_stocks/blob/e0c3febdda78a3310ac207a0a9ab9819624bc57a/robin_stocks/orders.py#L275

**Comment by jmfernandes** [comment]
removed the stop price check. Y'all are adults.
