### ISSUE TITLE
flaw in general order placer

### ISSUE THREAD

**Issue by klepsydra** [jmfernandes/robin_stocks#68]
There appears to be a flaw with the generic order function:
`
 robin_stocks.orders.order(symbol, quantity, orderType, limitPrice, stopPrice, trigger, side, timeInForce, extendedHours)
`
Namely, that all parameters must be supplied.  In particular, **stopPrice**, even when **trigger** == ‘_immediate_’ not ‘_stop_’

A situation arises in which it is impossible to place an order that is not trigger== ‘stop’, forced to specify a valid stop price, even if unwanted.

Try to skip the stopPrice parameter: 

>  TypeError: order() missing 1 required positional argument: 'stopPrice'

Try to specify stopPrice=**None**, like in the source for robin_stocks.orders.**order_buy_limit**: 

>  TypeError: float() argument must be a string or a number, not 'NoneType'

"None" in any quotes doesn't work either.

Okay, try  stopPrice=0:

>  {'stop_price': ['Ensure this value is greater than 0.']}

So try _stopPrice=0.01_, any unrealistic amount above 0: 

>  {'non_field_errors': ['Stop price provided, but trigger is not stop.']}

Finally, give up and switch from trigger='immediate' to trigger='stop'

>  {'non_field_errors': ['Extended hours orders cannot have stop price.']}

...which itself is a whole other bug/issue.

**Comment by klepsydra** [comment]
Suggestion:  Stop Price should be optional

**Comment by jmfernandes** [comment]
fixed and pushed to pypi version 0.9.9.6. also added extendedhours option to all stock orders.
