### ISSUE TITLE
Querying options on stock with no options returns info for all stocks?

### ISSUE THREAD

**Issue by mullenba** [jmfernandes/robin_stocks#74]
running the command:
`result = robin_stocks.options.find_tradable_options_for_stock("DPW)`

...seems to return options for all stocks, meaning dozens of pages (before I force quit).  Testing in helper.request_get() shows the following sample for the first returned page.

> {'next': 'https://api.robinhood.com/options/instruments/?cursor=cD0yMDIwLTAxLTA0KzAyJTNBMTUlM0ExMy41NjQyNzYlMkIwMCUzQTAw&state=active&tradability=tradable', 'previous': None, 'results': [{'chain_id': '481f3b74-c6e9-498d-b7d2-ff2814c1b20c', 'chain_symbol': 'CLNE', 'created_at': '2020-01-04T02:15:16.085701Z', 'expiration_date': '2020-01-17', 'id': 'b8066ba6-6758-4ecc-a4cf-7326c309b1ca', 'issue_date': '2007-09-06', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'call', 'updated_at': '2020-01-04T02:15:16.085710Z', 'url': 'https://api.robinhood.com/options/instruments/b8066ba6-6758-4ecc-a4cf-7326c309b1ca/'}, {'chain_id': '481f3b74-c6e9-498d-b7d2-ff2814c1b20c', 'chain_symbol': 'CLNE', 'created_at': '2020-01-04T02:15:16.085648Z', 'expiration_date': '2020-06-19', 'id': 'ee1fb99e-0edb-4bec-bf0c-f6490b9cf72a', 'issue_date': '2007-09-06', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'call', 'updated_at': '2020-01-04T02:15:16.085656Z', 'url': 'https://api.robinhood.com/options/instruments/ee1fb99e-0edb-4bec-bf0c-f6490b9cf72a/'}, {'chain_id': '481f3b74-c6e9-498d-b7d2-ff2814c1b20c', 'chain_symbol': 'CLNE', 'created_at': '2020-01-04T02:15:16.085594Z', 'expiration_date': '2020-06-19', 'id': 'b6a8d663-71fa-4cc9-859d-1531be63abab', 'issue_date': '2007-09-06', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'put', 'updated_at': '2020-01-04T02:15:16.085603Z', 'url': 'https://api.robinhood.com/options/instruments/b6a8d663-71fa-4cc9-859d-1531be63abab/'}, {'chain_id': '481f3b74-c6e9-498d-b7d2-ff2814c1b20c', 'chain_symbol': 'CLNE', 'created_at': '2020-01-04T02:15:16.085539Z', 'expiration_date': '2020-02-21', 'id': 'f84aff59-a088-4a2b-ad18-7850c71d4bd1', 'issue_date': '2007-09-06', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'call', 'updated_at': '2020-01-04T02:15:16.085548Z', 'url': 'https://api.robinhood.com/options/instruments/f84aff59-a088-4a2b-ad18-7850c71d4bd1/'}, {'chain_id': '481f3b74-c6e9-498d-b7d2-ff2814c1b20c', 'chain_symbol': 'CLNE', 'created_at': '2020-01-04T02:15:16.085482Z', 'expiration_date': '2020-02-21', 'id': '55b25543-98c7-4e97-bc0a-bdfea07fc80a', 'issue_date': '2007-09-06', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'put', 'updated_at': '2020-01-04T02:15:16.085492Z', 'url': 'https://api.robinhood.com/options/instruments/55b25543-98c7-4e97-bc0a-bdfea07fc80a/'}, {'chain_id': '481f3b74-c6e9-498d-b7d2-ff2814c1b20c', 'chain_symbol': 'CLNE', 'created_at': '2020-01-04T02:15:16.085412Z', 'expiration_date': '2020-01-17', 'id': 'd7058005-1e53-4667-a176-c4809a5cceb5', 'issue_date': '2007-09-06', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'put', 'updated_at': '2020-01-04T02:15:16.085430Z', 'url': 'https://api.robinhood.com/options/instruments/d7058005-1e53-4667-a176-c4809a5cceb5/'}, {'chain_id': '84283172-6c6e-45a6-b96b-639316445139', 'chain_symbol': 'NYMX', 'created_at': '2020-01-04T02:15:15.288735Z', 'expiration_date': '2020-08-21', 'id': 'caa50759-0642-45bb-9220-d1344ea53fba', 'issue_date': '2011-08-16', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'put', 'updated_at': '2020-01-04T02:15:15.288744Z', 'url': 'https://api.robinhood.com/options/instruments/caa50759-0642-45bb-9220-d1344ea53fba/'}, {'chain_id': '84283172-6c6e-45a6-b96b-639316445139', 'chain_symbol': 'NYMX', 'created_at': '2020-01-04T02:15:15.288683Z', 'expiration_date': '2020-08-21', 'id': 'eb7b6831-9993-41f1-ab9f-98ac3d991ffa', 'issue_date': '2011-08-16', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}, 'rhs_tradability': 'untradable', 'state': 'active', 'strike_price': '5.0000', 'tradability': 'tradable', 'type': 'call', 'updated_at': '2020-01-04T02:15:15.288691Z', 'url': 'https://api.robinhood.com/options/instruments/eb7b6831-9993-41f1-ab9f-98ac3d991ffa/'}, {'chain_id': '84283172-6c6e-45a6-b96b-639316445139', 'chain_symbol': 'NYMX', 'created_at': '2020-01-04T02:15:15.288630Z', 'expiration_date': '2020-05-15', 'id': '19353d6d-03ed-429b-adc3-b4e5a7c1c6ef', 'issue_date': '2011-08-16', 'min_ticks': {'above_tick': '0.10', 'below_tick': '0.05', 'cutoff_price': '3.00'}...

**Comment by beasthenry** [comment]
same
![image](https://user-images.githubusercontent.com/18081206/74124179-6daa9300-4b9f-11ea-825a-a997959a93ad.png)

**Comment by jmfernandes** [comment]
should be fixed in 1.0.0.2
