### ISSUE TITLE
400 Client Error

### ISSUE THREAD

**Issue by Mahnastanator** [jmfernandes/robin_stocks#8]
Hey Joshua,

Excellent work with the robin_stocks project!

I've been working on a program for about a week and a half and have been able to execute orders. However, in the last two days when I am placing market orders, I am running into a "400 Client Error: Bad Request for url" (Stop loss and limit still work). I have tried many different stocks, and I can still order from the app. Also from the start, I have been getting that error when trying to check day trades.

I was wondering if you ever ran into this problem, or if you have any ideas to solve it.

Thanks!

**Comment by jmfernandes** [comment]
Hello,

If you don't have enough "buying power" then you will get a bad request error. Was that the problem?

**Comment by Mahnastanator** [comment]
It was not, but today it is working fine. My Theory: I was doing a lot of
testing (ordering and canceling), Robinhood perhaps put a hold on my
account for placing orders externally.

Cheers!

**Comment by jmfernandes** [comment]
perhaps. The same has happened to me. Glad its working now!
