### ISSUE TITLE
Buying stocks when sub-pennies are quoted?

### ISSUE THREAD

**Issue by giterdun345** [jmfernandes/robin_stocks#81]
To my understanding SEC's NMS 612 is written to prevent prices above $1 to be displayed with subpenny values. Brokerages cannot accept orders or display quotes with more than 2 places after the decimal if the price is higher than a dollar. Yet they may be in violation of the rules because whenever I want to buy a stock that has subpenny increments, it shows and I am stopped with the message 'price': ["Prices above $1.00 can't have subpenny increments."] Is there anyway around this with your script? I have tried different approaches but to no avail. Thanks in advance.

**Comment by jmfernandes** [comment]
Are you sure you are using the latest version? The code is written to round any price above 0 to 2 decimal places. 

What order are you trying to place?

**Comment by giterdun345** [comment]
I used pip install but I don't think that has the current version. I cloned
'!pip install git+git://github.com/jmfernandes/robin_stocks.git --user' and
was successful. It took me a while to figure it out but all good now. Just
a heads up; thank you!
