### ISSUE TITLE
Unable to sell short call which is covered by a long call

### ISSUE THREAD

**Issue by eliezerp3** [jmfernandes/robin_stocks#83]
Sort of an interesting bug. I have calls expiring in about 3 months. On robinhood itself, I can sell ones expiring soon as they are covered by the long ones. But on the api for some reason it says I don't have enough shares (collateral) to sell a call. Anyone know whats going on?

**Comment by jmfernandes** [comment]
It's probably because the function you are calling is trying to "sell to open" instead of "sell to close". Can the function call that is giving you the error?

**Comment by eliezerp3** [comment]
I am using orders.order_sell_option_limit(). Is there seperate functions to sell to open and sell to close? What's the other one?

**Comment by eliezerp3** [comment]
Seems your right. It is trying to sell an existing call instead of writing a new one. Is there a different function that writes a call? Love your this api u made. Really appreciate it.

**Comment by eliezerp3** [comment]
I see someone made a pull request to fix this issue. Would you be able to merge it  please?

**Comment by jmfernandes** [comment]
@eliezerp3 should be fixed now. Added a new parameter to both order_sell_option_limit and order_buy_option_limit where you can specify if you want to have an 'open' position effect or a 'close' position effect. so now you can buy to open, buy to close, sell to open, and sell to close.
