### ISSUE TITLE
Trying to pull option chain data

### ISSUE THREAD

**Issue by AmeliorateOr** [jmfernandes/robin_stocks#9]

**Comment by AmeliorateOr** [comment]
Hello,

I'm trying to use your find_options_for_list_of_stocks_by_expiration_date function to pull the option chain data and it initiates but before completion it gives me an error. 

403 Client Error: Forbidden for url: https://api.robinhood.com/marketdata/options/742714ba-dfbc-4f7c-aa15-915a3e5fa9ca/
Traceback (most recent call last):
  File "<pyshell#39>", line 1, in <module>
    optionData = r.optionData = r.find_options_for_list_of_stocks_by_expiration_date('SPY',expirationDate = '2019-01-11', optionType='both', info = None)
  File "C:\Users\'User Info'\AppData\Roaming\Python\Python37\site-packages\robin_stocks\options.py", line 308, in find_options_for_list_of_stocks_by_expiration_date
    item.update(marketData)
TypeError: 'NoneType' object is not iterable

As I'm an absolute novice to coding and was finally able to get the proper path in place to operate pip in cmd after trial and error for 5 hours yesterday, any and all help is greatly appreciated. The first 10,000 hours is always the hardest I suppose :)

**Comment by AmeliorateOr** [comment]
I was able to get this to operate if I didn't use the symbol 'SPY' . Is there some sort of restriction on SPY on Robinhood's end? 

Even though it ran properly using AAPL and FB for example, I still can not get the results the print? Is there something I'm missing to get the print out? 

I tried this: 

>>> for item in optionData:
	      print(' price -',item['strike_price'],' exp - ',item['expiration_date'],' symbol - ',item['chain_symbol'],' delta - ',item['delta'],' theta - ',item['theta'])
	   

When I hit enter, nothing shows. No errors, etc. Just an empty new line below. 

Any tips to cross this hurdle and the non-accessibility to the SPY symbol?

**Comment by Mahnastanator** [comment]
Is this the function you are still using?: find_options_for_list_of_stocks_by_expiration_date

what happens when you use?: robin_stocks.options.find_options_for_stock_by_expiration

Also, here and there I have run into problems returning/buying certain stocks. I think it is a problem with Robinhoods end. You said this didn't give an error, but let me know if you get a '400 error', that's what I have run into.

**Comment by jmfernandes** [comment]
Hello,

Sorry I'm late to respond. I believe you have the code working now and the reason you are getting None is because today is 2019-1-11 and the options are no longer available. I've been running the function with both SPY and regular stocks like F and it appears to be working for me. Let me know if you get it working. Here is my code.

`import robin_stocks as r
login = r.login('joshfernandes@mac.com','ThisIsntMyRealPassword')

stuff = find_options_for_list_of_stocks_by_expiration_date('spy',expirationDate='2019-01-18')

for item in stuff:
    print(item)`

**Comment by jmfernandes** [comment]
BTW, i just pushed out a new version of the code where I changed *inputSymbols to just inputSymbols. If you install version 0.9.8 you can now do

    import robin_stocks as r
    login = r.login('joshfernandes@mac.com','ThisIsntMyRealPassword')

    stuff = find_options_for_list_of_stocks_by_expiration_date(['spy','f','tsla'],'2019-01-18')

    otherstuff = find_options_for_list_of_stocks_by_expiration_date('spy','2019-01-18')

    for item in stuff:
        print(item)

no longer need to explicitly say expirationDate=

**Comment by AmeliorateOr** [comment]
Hi J! 

Thanks for getting back to me on this! It seems to work now, I believe you are right about them already being past expiry.  The [None] response doesn't show up anymore.

Now that I can see this data, how to parse it properly for the specific data I'd like to see? Is there documentation I can read so I don't have to bother you unless I hit a wall. 

For instance right now all I'd like to see the option chain for SPY but only want the strikes, bid, ask, last, volume, open interest. I'm trying to run this every 15 min to get a feel for the activity of the options market throughout the day and then save it to a file for later review. 

Any pointers would be greatly appreciated as this is my first attempt to run/learn code. I have no idea how this stuff operates from a language infrastructure perspective which is disheartening as I mostly just copy/paste and try to "think" about what is trying to be achieved but have no idea how python is supposed to be executed. I'm brute forcing through the pain and it's been painful and I'm moving at a snail's pace but I got the chain with your help and this .api . So tyvm for this so far! I'm really enjoying this and its potential.

**Comment by AmeliorateOr** [comment]
> BTW, i just pushed out a new version of the code where I changed *inputSymbols to just inputSymbols. If you install version 0.9.8 you can now do
> 
> ```
> import robin_stocks as r
> login = r.login('joshfernandes@mac.com','ThisIsntMyRealPassword')
> 
> stuff = find_options_for_list_of_stocks_by_expiration_date(['spy','f','tsla'],'2019-01-18')
> I think this needs to be stuff = r.find_options_for_list_of_stocks_by_expiration_date(['spy','f','tsla'],'2019-01-18') . Without the r. I didn't get it to operate properly. 
> otherstuff = find_options_for_list_of_stocks_by_expiration_date('spy','2019-01-18')
> 
> for item in stuff:
>     print(item)
> ```
> no longer need to explicitly say expirationDate=
I'll definitely download the newest version. Thanks.

**Comment by AmeliorateOr** [comment]
When I run the above line you suggested I get this error:

>>> for item in stuff:
	print(stuff['ask_price'])

	
Traceback (most recent call last):
  File "<pyshell#18>", line 2, in <module>
    print(stuff['ask_price'])
TypeError: list indices must be integers or slices, not str


Any idea what I'm missing? 


-------------------------------------------------

You asked for any examples that would be helpful: 
An example of how to pull an option chain (which you have already), with a specific example on pulling certain items from the chain, as well as being able to set it on a timer/loop as you mentioned so others (myself included) could pull data throughout the day and really put this thing to some good use. That would be great! :)

**Comment by jmfernandes** [comment]
oops. meant item['ask_price']

and yeah an updated loop sounds great. I'll write up an example script maybe next week.
