### ISSUE TITLE
Invalid direction for selling option limit order

### ISSUE THREAD

**Issue by danielstallworthmit** [jmfernandes/robin_stocks#90]
`r. orders.order_sell_option_limit('close', price, ticker, quantity, dt, strike, 'call', 'gfd')`

Returns the following when attempting to close out a long call option:
`{'detail': 'This is an invalid direction for a sell-order.'}`

I switched the direction to be `credit` on sell close in the orders.py file and it works.
Seems like the API expects direction to always be credit on sell as it only fails on `positionEffect = 'close'`. Though I have not tested this on put options or much more extensively than my use case.

**Comment by jmfernandes** [comment]
fixed in 1.0.0.3. added a creditOrDebit parameter so you can specify if its supposed to be credit or debit.

**Comment by GrainsofSalt** [comment]
I am getting the same error for the exact same thing. I assumed the creditOrDebit would be "debit" considering that is what I used to buy. Does this parameter always need to be "credit" and if so why is there an option?
