### ISSUE TITLE
Can't get and cancel crypto orders

### ISSUE THREAD

**Issue by rydailey** [jmfernandes/robin_stocks#91]
Methods for getting and canceling crypto orders don't exist. It looks like the endpoints are already available in urls, just no methods. Consider adding:

get_crypto_order_info(orderID)
get_all_open_crypto_orders(info = None)
cancel_crypto_order(orderID)
cancel_all_open_crypto_orders()

**Comment by MaxBan** [comment]
+1

**Comment by jmfernandes** [comment]
Done. These are all the order related functions that exists now.

get_all_stock_orders          
 get_all_option_orders
get_all_crypto_orders
get_all_open_stock_orders
get_all_open_option_orders
get_all_open_crypto_orders
get_stock_order_info
get_option_order_info
get_crypto_order_info
find_stock_orders
cancel_all_stock_orders
cancel_all_option_orders
cancel_all_crypto_orders
cancel_stock_order
cancel_option_order
cancel_crypto_order
